language: rust
addons:
  apt:
    packages:
    - libibverbs1
    - ninja-build
    - cmake
    - cmake-data
    sources:
    - george-edison55-precise-backports # cmake 3.2.3
rust:
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
